[package]
name = "cc13x2"
version = "0.1.0"
authors = ["Robert Keith <robertfkeith@me.com>"]

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
kernel = { path = "../../kernel" }
cc26xx = { path = "../cc26xx" }
